# Generated by Django 4.1.7 on 2023-05-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociazionePasti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapasto', models.DateField()),
                ('numero_CMD', models.CharField(max_length=10)),
                ('Colazione', models.CharField(max_length=1, null=True)),
                ('Pranzo', models.CharField(max_length=1, null=True)),
                ('Cena', models.CharField(max_length=1, null=True)),
                ('Sandwich', models.CharField(max_length=1, null=True)),
                ('Lavanderia', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=50)),
                ('numero_CMD', models.CharField(max_length=10)),
            ],
        ),
    ]
