# Generated by Django 4.1.7 on 2023-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotamensa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociazioneAtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapasto', models.DateField()),
                ('numero_CMD', models.CharField(max_length=10)),
                ('Colazione', models.CharField(max_length=1, null=True)),
                ('Pranzo', models.CharField(max_length=1, null=True)),
                ('Cena', models.CharField(max_length=1, null=True)),
                ('Sandwich', models.CharField(max_length=1, null=True)),
                ('Lavanderia', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AssociazionePasti',
        ),
    ]
